name: Behaviour Tests

# thanks go to derhansen for demo extension https://github.com/derhansen/gha_demo
# and blog https://www.derhansen.de/2020/05/typo3-extension-testing-with-github-actions.html


on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4


      # start db
      #- name: Start MySQL
      #  run: sudo /etc/init.d/mysql start

      #- name: Initialize TYPO3 environment
      #  run: cp Build/envs/.env.github .env

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies
        run: composer install --no-progress

      # acceptance
      #- name: Setup Runner Database
      #  run: |
      #    mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS crawler_gh;'
      #    gzip -dc .devbox/build-files/db.sql.gz | mysql -uroot -proot -h127.0.0.1 crawler_gh

      #- name: Initialize TYPO3 environment
      #  run: |
      #    mkdir config && cd config && ln -s ../Build/sites && cd -
      #    cp Build/LocalConfiguration.php .Build/Web/typo3conf/
      #    .Build/bin/typo3cms install:generatepackagestates
      #    .Build/bin/typo3cms database:update

      - name: Run PHP webserver
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          sed -i -e "s/GITHUB_DOMAIN/$APP_IP:8888/" Tests/Acceptance/_envs/github.yml
          php -S 0.0.0.0:8888 -t src/ &> php.log.txt &
          sleep 2;
      - name: Test PHP webserver and initialize TYPO3 cache
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          curl "$APP_IP:8888"
      - name: Run chromedriver
        run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &

      - name: Codeception Acceptance Tests
        run: |
          export APP_IP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh -t 60 $APP_IP:8888
          ./wait-for-it.sh -t 60 localhost:9515
          vendor/bin/codecept run -c Tests/Acceptance.suite.yml --env=github --html

      - name: Upload Codeception output
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: codeception-results
          path: Tests/Acceptance/_output/

      - name: Upload PHP log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: php-log
          path: php.log.txt

      #- uses: shallwefootball/s3-upload-action@master
      #  #if: ${{ failure() }}
      #  with:
      #    aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      #    aws_bucket: ${{ secrets.AWS_BUCKET }}
      #    source_dir: 'Tests/Acceptance/_output/'
      #    destination_dir: ''
