name: Branch
on: [push, pull_request]

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nelonoel/branch-name@v1.0.1
      - run: echo ${BRANCH_NAME}