name: Branch & Path

on:
  #pull_request:
   # branches:
   #   - "**"
   # paths:
   #   - '.github/workflows/BranchAndPath.yml'
   #   - 'README.md'
    
  push:
    branches:
      - "**"
    paths: 
      - '.github/workflows/BranchAndPath.yml'
      - 'README.md'


jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      #- run: echo ::set-env name=REPO_NAME::${{ github.event.repository.name }}
      - uses: actions/checkout@v1
      - run: | 
          echo "I'm running !!"
          echo "${{ github.event.repository.name }}"
